PAGE_HOME = 'https://stellarburgers.nomoreparties.site/'
C_USER = f'{PAGE_HOME}api/auth/register'
L_USER = f'{PAGE_HOME}api/auth/login'
D_USER = f'{PAGE_HOME}api/auth/user'
C_ORDER = f'{PAGE_HOME}api/orders'